# Generated by Django 4.1.5 on 2023-04-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokess', '0002_alter_jokes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokes',
            name='author',
            field=models.CharField(default='auth1', max_length=255),
            preserve_default=False,
        ),
    ]
